config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 root to: 'searches#index'

 resources :products do
    get :get_barcode, on: :collection
  end

resources :searches, only:[:index,:new, :create], shallow: true do
    resources :stocks, only:[:index, :show], shallow: true do
      resources :reviews, only:[:show, :new, :create]
      resources :favorites, only:[:create]
      resources :baskets, only:[:create]
    end
end
  resources :favorites, only:[:index, :destroy]
  resources :baskets, only:[:index, :destroy]
  resources :itinaries, only: [:index]
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  belongs_to :stock
  validates_uniqueness_of :user, scope: :stock
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def index
    @baskets = Basket.all



     @stocks_id = []
    # @products.each do |product|
      # product_stocks = Stock.where(product_id: @product.id)
      # basket_stocks = Basket.

      @baskets.each do |basket|
        @stocks_id << basket.stock_id
      end

      @stocks = Stock.where(id: @stocks_id)

      @shops_id = []
      @stocks.each do |stock|
        @shops_id << stock.shop_id
      end

      @shops = Shop.where(id: @shops_id)

      @markers = @shops.map do |shop|
        {
        lat: shop.latitude,
        lng: shop.longitude,
        image_url: helpers.asset_url('lily.png')
      }
      end
  end

  def new
    @basket = Basket.new
  end

  def create

    if Stock.find(params[:stock_id]) == nil
      @stock = Stock.find(params[:id])
    else
      @stock = Stock.find(params[:stock_id])
    end

    @basket = Basket.new()
    @basket.user_id = current_user[:id]
    @basket.stock_id = @stock.id


    if @basket.save

    else
      redirect_to baskets_path, :notice => "Ce produit est déjà dans le panier."
    end
  end

  def destroy
    @basket = Basket.find(params[:id])
    @basket.destroy!
    redirect_to baskets_path, :notice => "Ce produit a bien été supprimé du panier."
  end
end

app/views/baskets/index.html.erb
<div class="favorite-bg">


  <nav class="navbar navbar-expand-sm bg-transparent justify-content-between" id="nav" style="position: absolute; z-index: 10; width: 100%">

    <!-- Logo à gauche -->
    <%= link_to "/" do %>
        <%= image_tag "lily_35.png" %>
    <% end %>


    <!-- Burger -->
    <div class="dropdown dropleft">
      <button class="btn bg-transparent border-transparent shadow-none px-1" type="button" data-toggle="dropdown"><i class="fas fa-bars fa-1x" style="color: white;"></i>
          </button>
        <% if user_signed_in? %>

          <div class="dropdown-menu rounded border-0 shadow-none" aria-labelledby="dropdownMenu2">
            <%= link_to baskets_path do %>
            <button class="dropdown-item" type="button">Panier</button>
            <% end %>
            <%= link_to favorites_path do %>
            <button class="dropdown-item shadow-none" type="button">Favoris</button>
            <% end %>
            <%#= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <button class="dropdown-item shadow-none" type="button">Log out</button>
            <% end %>
          </div>
        <% else %>
          <div class="dropdown-menu rounded border-0 shadow-none" aria-labelledby="dropdownMenu2">
            <%= link_to new_user_session_path do %>
            <button class="dropdown-item shadow-none" type="button">Login</button>
            <% end %>
          </div>
        <% end %>
    </div>

  </nav>

<div class="d-flex justify-content-center p-2">
  <h1 class="text-center text-white">Panier <i class="fas fa-shopping-basket" style="font-size: 30px;"></i></h1>
</div>

  <div class="container">

    <% @baskets.each do |basket| %>
    <div class="row d-flex bg-white rounded shadow border m-2 border-0">
      <div class="col-sm-2 w-25 p-0">
       <i class="img-resize rounded"><%= cl_image_tag basket.stock.product.photo.key %></i>
      </div>
      <div class="col-sm-9 py-1 w-50">
        <div class="d-flex w-100">
          <div class="d-block">
            <strong><p class="m-0"><%= basket.stock.product.name %></p></strong>
            <i><%= basket.stock.product.brand %></i>
          </div>
        </div>
      </div>
      <div class="col-sm-1 w-25 d-flex align-items-center">
        <%= button_to basket_path(basket), method: :delete, class: " btn p-0 m-0 bg-transparent border-O" do %>
          <i class="far fa-times-circle" id="btn-suppr" style="color: #bbbbbb;"></i>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

<div class="container text-center">
  <div class="row">
    <div class="col-12">

      <%= link_to itinaries_path do %>
        <button class='btn btn-warning shadow-none rounded rounded-pill px-5 m-4'>
          <i class="fas fa-route shadow-none " style="color: white; font-size: 40px;"></i>
        </button>
      <% end %>

    </div>
  </div>
</div>

</div> <!--  Background -->