config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 root to: 'searches#index'

 resources :products do
    get :get_barcode, on: :collection
  end

resources :searches, only:[:index,:new, :create], shallow: true do
    resources :stocks, only:[:index, :show], shallow: true do
      resources :reviews, only:[:show, :new, :create]
      resources :favorites, only:[:create]
      resources :baskets, only:[:create]
    end
end
  resources :favorites, only:[:index, :destroy]
  resources :baskets, only:[:index, :destroy]
  resources :itinaries, only: [:index]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates_uniqueness_of :user, scope: :product
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
    @favorites.each do |favorite|
      @stock = Stock.where(product_id: favorite.product_id)
    end
  end

  def new
    @favorite = Favorite.new
  end

  def create
    @stock = Stock.find(params[:stock_id])
    @favorite = Favorite.new()
    @favorite.user_id = current_user[:id]
    @favorite.product_id = @stock.product.id

    if @favorite.save
      redirect_to stock_path(@stock.id), :notice => "Ce produit a bien été ajouté."
    else
      redirect_to stock_path(@stock.id), :notice => "Ce produit est déjà dans les favoris."
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy!
    redirect_to favorites_path, :notice => "Ce favori a bien été supprimé."
  end
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/index.html.erb
<div class="favorite-bg">


  <nav class="navbar navbar-expand-sm bg-transparent justify-content-between" id="nav" style="position: absolute; z-index: 10; width: 100%">

    <!-- Logo à gauche -->
    <%= link_to "/" do %>
        <%= image_tag "lily_35.png" %>
    <% end %>


    <!-- Burger -->
    <div class="dropdown dropleft">
      <button class="btn bg-transparent border-transparent shadow-none px-1" type="button" data-toggle="dropdown"><i class="fas fa-bars fa-1x" style="color: white;"></i>
          </button>
        <% if user_signed_in? %>

          <div class="dropdown-menu rounded border-0 shadow-none" aria-labelledby="dropdownMenu2">
            <%= link_to baskets_path do %>
            <button class="dropdown-item" type="button">Panier</button>
            <% end %>
            <%= link_to favorites_path do %>
            <button class="dropdown-item shadow-none" type="button">Favoris</button>
            <% end %>
            <%#= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <button class="dropdown-item shadow-none" type="button">Log out</button>
            <% end %>
          </div>
        <% else %>
          <div class="dropdown-menu rounded border-0 shadow-none" aria-labelledby="dropdownMenu2">
            <%= link_to new_user_session_path do %>
            <button class="dropdown-item shadow-none" type="button">Login</button>
            <% end %>
          </div>
        <% end %>
    </div>

  </nav>


  <div class="d-flex justify-content-center p-2">
    <h1 class="text-center text-white">Favoris <i class="fas fa-heart" style="font-size: 30px;"></i></h1>
  </div>

  <div class="container">

    <% @favorites.each do |favorite| %>

    <div class="row d-flex bg-white rounded shadow border m-2 border-0" style="min-height: 120px;">

      <div class="col-sm-2 w-25 p-0">
       <i class="img-resize rounded"><%= cl_image_tag favorite.product.photo.key %></i>
      </div>
      <div class="col-sm-9 py-1 w-50">
        <div class="d-flex w-100">
          <div class="d-block">
            <strong><p class="m-0"><%= favorite.product.name %></p></strong>
            <i><%= favorite.product.brand %></i>
            <p class="overflow-auto p-O" style="height: 70px; font-size: 13px;"><%= favorite.product.description %></p>
          </div>
        </div>
      </div>
      <div class="col-sm-1 w-25 d-flex align-items-center">
        <%= button_to favorite_path(favorite),method: :delete, class: " btn p-0 m-0 bg-transparent border-O" do %>
          <i class="far fa-times-circle" id="btn-suppr" style="color: #bbbbbb;"></i>
        <% end %>
        <%= link_to search_stocks_path(favorite.product.id) do %>
        <i class="fa fa-search" id="btn-search"></i>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>