config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 root to: 'searches#index'

 resources :products do
    get :get_barcode, on: :collection
  end

resources :searches, only:[:index,:new, :create], shallow: true do
    resources :stocks, only:[:index, :show], shallow: true do
      resources :reviews, only:[:show, :new, :create]
      resources :favorites, only:[:create]
      resources :baskets, only:[:create]
    end
end
  resources :favorites, only:[:index, :destroy]
  resources :baskets, only:[:index, :destroy]
  resources :itinaries, only: [:index]
end

app/models/stock.rb
class Stock < ApplicationRecord

  belongs_to :shop
  belongs_to :product
  has_many :reviews, dependent: :destroy
  has_many :baskets, dependent: :destroy


end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController



  def index

      # ---------------#ElasticSearch
    # @products = Product.all
    # params[:query].split(" ").each do |word|
    #   @products = @products.where(id: @products.search(word).map(&:id))
    # end

    # @products = Product.search(params[:query], emoji: true)
    #-----------------#ElasticSearch


    #@products = Product.all #'sans Elastic'

   @product = Product.find(params[:search_id])


     @stocks = []
    # @products.each do |product|
      product_stocks =  Stock.where(product_id: @product.id)

      product_stocks.each do |stock|
        @stocks << stock
      end

    @basket = Basket.new
    @basket_user = Basket.where(user_id: current_user[:id]).map(&:stock_id)



      @markers = @stocks.map do |stock|
        {
        lat: stock.shop.latitude,
        lng: stock.shop.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { shop: stock.shop , product: stock.product, stock: stock, basket: @basket}),
        image_url: helpers.asset_url('lily_omb.png')
      }
      end

  end

  def show

    @basket = Basket.new
    @basket_user = Basket.where(user_id: current_user[:id]).map(&:stock_id)

    @review = Review.new
    @reviews = Review.where(stock_id: params[:id])

    @favorite = Favorite.new
    @favorite_user = Favorite.where(user_id: current_user[:id]).map(&:product_id)

    @stock = Stock.find(params[:id])
    @product = @stock.product
    @rating = @stock.reviews.map(&:rating)
    @shop = @stock.shop
    @day_of_week = @shop.time_tables.map(&:day_of_week)

    @markers = [{
        lat: @stock.shop.latitude,
        lng: @stock.shop.longitude,
        image_url: helpers.asset_url('lily.png')
    }]

    if @shop.time_tables == []
      @open = "Aucuns horaires"
    else
      gestion_horaire
    end

    if @rating != []
      @rating_score = (@rating.sum / @rating.count).truncate(2)
      rating_star
      rating_half_star
    else
      @star = 0
      @halfstar = 0
      @rating_score = 0
      @rating = 0
    end
  end


private


  ###DATE#####

  def gestion_horaire

    if (open_today? && (Time.now < Time.new(Time.now.year, Time.now.month, Time.now.day, good_opening_hour, 00, 00))) #Matin avant ouverture

        time_second = Time.new(Time.now.year, Time.now.month, Time.now.day, good_opening_hour, 00, 00) - Time.now
        time_hour = time_second / 3600
        hours = time_hour.floor
        minutes = ((time_hour - hours) * 60).to_i
        if minutes.to_s.length < 2
            minutes = "0#{minutes}"
          end
        @open = "Fermé"
        @fermeture = "Ouvre à #{good_opening_hour}:00 (dans #{hours}h:#{minutes}m) "


      elsif open_today? && (Time.now > Time.new(Time.now.year, Time.now.month, Time.now.day, good_closing_hour, 00, 00)) #Soir aprés fermeture
         #!!!!
        if Time.now.wday == @day_of_week.last
                                                                       #Si c'est le dernier jour d'ouverture
          @open = "Fermé"
          @fermeture = "Ouvre #{wich_day(@day_of_week.first)} à #{good_opening_hour}h:00m" #Le else possible
        else                                                                                                       #Si le magasin est ouvert le lendemain
          time_second = Time.new(Time.now.year, Time.now.month, Time.now.day, 23, 59, 59) - Time.now
          time_hour = time_second / 3600
          hours = time_hour.floor + good_opening_hour
          minutes = ((time_hour - hours) * 60).to_i
          if minutes.to_s.length < 2
            minutes = "0#{minutes}"
          end
          @open = "Fermé"
          @fermeture = "Ouvre demain à #{good_opening_hour}h"
        end

        # Dans la plage horaire d'ouverture
      elsif   open_today? && ( (Time.new(Time.now.year, Time.now.month, Time.now.day, good_opening_hour, 00, 00) < Time.now)  && (Time.now < Time.new(Time.now.year, Time.now.month, Time.now.day, good_closing_hour, 00, 00) ) )
        time_second = Time.new(Time.now.year, Time.now.month, Time.now.day, good_closing_hour, 00, 00) - Time.now
        time_hour = time_second / 3600
        hours = time_hour.floor
        minutes = ((time_hour - hours) * 60).to_i
        if minutes.to_s.length < 2
            minutes = "0#{minutes}"
          end
        @open = "Ouvert"

        if (Time.new(Time.now.year, Time.now.month, Time.now.day, good_closing_hour, 00, 00) - Time.now <= 4680)    #Si c'est 1h30 avant la fermeture
          @fermeture = "Ferme bientôt. #{good_closing_hour}:00 (dans #{hours}h:#{minutes}m)"
        else
          @fermeture = "Ferme à #{good_closing_hour}:00 (dans #{hours}h:#{minutes}m)"                            #Si il reste plus de 1h30 avant la fermeture
        end
      else
        @open = "Fermé"
        @fermeture = "Ouvre #{wich_day(@day_of_week.first)} à #{good_opening_hour}h:00m"
      end


  end

  def open_today?
    @day_of_week.include?(Time.now.wday)
  end

  def good_opening_hour
      if @opening_hour == nil
        @opening_hour = TimeTable.where("shop_id = '#{@shop.id}' and day_of_week = '#{@day_of_week.first}'").first.opened_at
      elsif Time.now.wday != @day_of_week.last
        @opening_hour = TimeTable.where("shop_id = '#{@shop.id}' and day_of_week = '#{Time.now.wday + 1}'").first.opened_at
      else
        @opening_hour = TimeTable.where("shop_id = '#{@shop.id}' and day_of_week = '#{Time.now.wday}'").first.opened_at
      end
  end

    def good_closing_hour
      @shop.time_tables.find_by(day_of_week: Time.now.wday).closed_at
    end

    def wich_day(date_number)
      case date_number
      when 0
        return "Dimanche"
      when 1
        return "Lundi"
      when 2
        return "Mardi"
      when 3
        return "Mercredi"
      when 4
        return "Jeudi"
      when 5
        return "Vendredi"
      when 6
        return "Samedi"
      end
    end


  #Rating######

  def rating_star
    if @rating.count > 0
      @star = @rating.sum / @rating.count
    else
      @star = 0
    end
  end

  def rating_half_star
    if @star > 1
      rating_score = (@rating.sum / @rating.count).to_s.split(",")
      rating_integer = rating_score[0].to_i
      rating_float = rating_score[1].to_f
      if rating_float >= 0.7 && rating_float <= 0.3
        return @halfstar = 1
      else
        return @halfstar = 0
      end
    else
      @halfstar = 0
    end
  end

end

app/views/stocks/_index_review.html.erb
<!-- Button trigger modal -->
<!-- Button trigger modal -->
<button type="button" class="btn btn-warning text-white" data-toggle="modal" data-target="#exampleModalLong">
  Voir les avis
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Avis</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if @reviews.present? %>
          <% @reviews.each do |review| %>
          <div class="card p-3">
            <div class="d-flex py-1 text-yellow">
              <% review.rating.times do  %>
                <i class="fas fa-star"></i>
              <%end  %>
            </div>
            <%= review.comment %>
          </div>
          <% end %>
        <% else %>
            <p>Soyez le premier à donner votre avis</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/stocks/_info_window.html.erb
<div class="container p-0">
  <div class="text-center">
    <div class="img-size">
      <i><%= cl_image_tag product.photo.key%></i>
    </div>
    <div>
      <h6 class="my-2"><%= product.name %></h6>
      <p class="m-0"><%= shop.name %></p>
      <p><%= shop.address %></p>

    <div class="text-center px-4">
      <h4><%="#{stock.price}€" %></h4>
    </div>
    <div class="d-flex justify-content-around align-items-center p-2">

      <% if @basket_user.include? stock.id  %>
        <%= simple_form_for [stock, basket] do |f| %>
          <%= button_tag :submit, class: 'btn border shadow-none' do %>
          <i class="fas fa-shopping-basket shadow-none" style="color: #cfcfcf; cursor: auto; font-size: 20px;"></i>
          <% end %>
        <% end %>
      <% else %>
        <%= simple_form_for [stock, basket] do |f| %>
          <%= button_tag :submit, class: 'btn btn-outline-success shadow-none' do %>
          <i class="fas fa-shopping-basket shadow-none " style="color: #A8D384; font-size: 20px;"></i>
          <% end %>
        <% end %>
      <% end %>

      <%= link_to stock_path(stock.id) do %>
        <button class="btn btn-warning px-2 py-1">
          <i class="fas fa-chevron-right" style="color: white;"></i><i class="fas fa-chevron-right" style="color: white;"></i>
        </button>
      <% end %>

    </div>
  </div>
</div>


<!--     <div class="d-flex justify-content-between align-items-center mb-2">
      <button class="btn p-0 m-0 bg-warning border-O shadow-none" data-toggle="modal" data-target="#ModalNewBasket">
        <i class="fas fa-shopping-basket shadow-none" style="color: white; cursor: auto; font-size: 20px;"></i>
      </button>
    </div> -->

app/views/stocks/_newreview.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn p-0 m-0 bg-transparent border-O shadow-none" data-toggle="modal" data-target="#exampleModalCenter">
  <i class="far fa-edit" style="color: #F4AA5B; cursor: pointer;"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Ajouter un avis</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= simple_form_for [@stock, @review] do |f| %>
            <%= f.input :comment, label: "Commentaire", error: "Veuillez renseigner ce champ" %>
            <%= f.input :rating, collection: 0..5, label: "Note", error: "La note doit être comprise entre 0 et 5" %>
            <%= f.submit 'Créer mon avis', class: 'btn btn-success ml-0' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stocks/index.html.erb
<!-- nav-bar -->


<%= render 'shared/navbar' %>
<div id ="mask" style="background-color: rgba(0,0,0,0.3); position: absolute; z-index: 8; width:100vh; height:100vh; display: none;"></div>
  <!-- map -->
  <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <!--   <div id="search-add" class="btn-circle-add">
      <i class="fas fa-compass" style="color: #F4AA5B; font-size: 20px;"></i>
    </div> -->

<button id="btn-add" class="btn btn-circle-add border-0 rounded rounded-pill shadow-none bg-white py-1 px-2"><i class="fas fa-map-marker-alt shadow-none " style="color: #ffcd3c; font-size: 30px"></i></button>
<div id="geocoder" class="geocoder shadow-none"></div>


  <!-- <div class="bg-white info-instruction-bis m-0 w-25 rounded">
    <div class="d-flex align-item-center p-1">
     <i class="fas fa-walking" style="font-size: 11px"></i>
     <p id="instructions-iti-bis" class="m-0 pl-1 text-center" style="font-size: 11px" ></p>
    </div>
  </div> -->
<script>

  const div = document.getElementById('geocoder');
  const displayS = (d) => {
    if (d.style.display === "none") {
      d.style.display = "block";
    } else {
      d.style.display = "none";
    }};
  const search = document.getElementById('btn-add');
  search.addEventListener('click', (event) => {
    displayS(div);
  });


</script>

app/views/stocks/show.html.erb
<!-- navbar -->
<%= render 'shared/navbar' %>

<!-- btn back -->
<%= link_to search_stocks_path(@stock.product.id) do%>
  <div class="btn rounded rounded-pill btn-circle bg-warning p-2"><i class="fas fa-chevron-right" style="color: white"></i></div>
<% end %>

<!-- btn instructions -->
<div class="dropdown dropright">
  <div class="btn rounded rounded-pill btn-circle-norm bg-success p-2" data-toggle="dropdown"><i class="fas fa-map-signs" style="color: white"></i></div>
  <ol class="dropdown-menu rounded border-0 p-2 w-75 overflow-auto" id="instructions-steps" style="background-color: rgba(0,0,0,0.7); max-height: 130px;">
  </ol>
</div>


<!-- btn address -->

<button id="btn-add-2" class=" btn btn-circle-add-2 border-0 rounded rounded-pill bg-white py-1 px-2 shadow-none"><i class="fas fa-map-marker-alt" style="color: #ffcd3c; font-size: 30px"></i></button>
<div id="geocoder-2" class="geocoder-2"></div>


<!-- map -->
<div class="" id="map-iti" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>


<div class="bg-white" style="height: 50vh;">


<!--   <div class="bg-white info-instruction m-0 w-25 rounded ">
    <div class="d-flex align-item-center p-1">
    <i class="fas fa-walking" style="font-size: 11px"></i>
    <p id="instructions-iti" class="m-0 pl-1 text-center" style="font-size: 11px" ></p>
    </div>
  </div> -->

  <div class="bg-white font-color-grey" id="card_show">

    <!-- Infos shop -->
    <div class="shop_part text-center shadow-sm p-3 bg-white rounded">
    <div class="btn-basket">
      <% if @basket_user.include? @stock.id  %>
        <%= simple_form_for [@stock, @basket] do |f| %>
          <%= button_tag :submit, class: 'btn border shadow-none' do %>
          <i class="fas fa-shopping-basket shadow-none" style="color: #cfcfcf; cursor: auto; font-size: 20px;"></i>
          <% end %>
        <% end %>
      <% else %>
        <%= simple_form_for [@stock, @basket] do |f| %>
          <%= button_tag :submit, class: 'btn btn-outline-success shadow-none' do %>
          <i class="fas fa-shopping-basket shadow-none " style="color: #A8D384; font-size: 20px;"></i>
          <% end %>
        <% end %>
      <% end %>
    </div>

      <div class="">
          <h4><%= @shop.name %></h4>
          <div class="d-flex justify-content-around align-items-center p-0 m-0">
            <div class="col-6 p-0">
              <% if @open == "Ouvert" %>
                 <p class="p-0 m-0 green-title ">
                  <%= @open %>
                </p>
              <% else %>
                 <p class="p-0 m-0 red-title">
                  <%= @open %>
                </p>
              <% end %>

              <p class="p-0 m-0"><%= @fermeture %></p>
            </div>
            <div class="col-6 p-0">
              <i class="fas fa-walking" style="font-size: 18px"></i>
              <p id="instructions-iti" class="m-0 p-0"></p>
            </div>
          </div>
      </div>
    </div>

    <!-- Infos product -->
    <div class="d-flex mt-2">
      <div class="col-6 p-0 m-0">
        <div class="product-description pt-1 px-2">
          <div class="d-flex justify-content-between align-items-center mb-2" style="max-height: 75px;">
            <h5><%= @product.name %></h5>
            <button class="btn p-0 m-0 bg-transparent border-O shadow-none" data-toggle="modal" data-target="#ModalNewFavorite"> <i class="fa fa-heart shadow-none"
              <% if @favorite_user.include? @stock.product.id  %>
              style="color: #f688bb; cursor: auto; font-size: 20px;"
              <% else %>
              style="color: gray; font-size: 20px;"
              <% end %>
            ></i></button>
          </div>
          <p><strong>Marque :</strong> <%= @product.brand %></p>
          <p class="mb-1"><strong>Qté :</strong> <%= @stock.quantity %></p>
          <p class="overflow-auto" style="max-height: 100px;"><%= @product.description %></p>
        </div>




      </div>

      <div class="col-6 text-center">

        <div class="img-size-large my-2">
          <%= cl_image_tag @product.photo.key%>
        </div>

        <div class="pric">
          <h3 class="mb-0"><%= @stock.price %> €</h3>
        </div>

              <!-- Rating -->
        <div class="d-flex px-2 justify-content-between">
          <!--<%# if @rating_score != 0 %>
            <p><%= @rating_score %></p>
          <%#end %>-->
          <div class="d-flex align-items-center">
            <% @star.times do  %>
              <i class="fas fa-star" style="font-size: 13px; color: #ffcc00;"></i>
            <%end  %>
            <% @halfstar.times do %>
              <i class="fas fa-star-half-alt" style="font-size: 13px; color: #ffcc00;"></i>
            <%end  %>
            <% if @rating != 0 %>
              <p class="m-0 pl-1"><%= " #{@rating.count} note(s)" %></p>
            <% end %>
          </div>

          <div>
            <%= render 'newreview' %>
          </div>
        </div>

        <div class="card overflow-auto ml-2 mr-5 mt-2" id="comments">
        <% if @reviews.present? %>
          <% @reviews.each do |review| %>
          <div class="">
            <div class="d-flex p-1 text-yellow">
              <% review.rating.times do  %>
                <i class="fas fa-star" style="font-size: 13px;"></i>
              <%end  %>
            </div>
            <p class="mb-1 border-bottom text-left"><%= review.comment %></p>
          </div>
          <% end %>
          <% else %>
            <p class="text-left">Soyez le premier à donner votre avis.</p>
          <% end %>
        </div>

      </div>

    </div>



<!-- <div id="instructions-steps"></div> -->

   <!--
  <h2><%#= @stock.shop.name %></h2>
   <%# if @rating_score != 0 %>
        <p><%= @rating_score %></p>
      <%#end %>
      <%# @star.times do  %>
        <i class="fas fa-star"></i>
      <%#end  %>
      <%# @halfstar.times do %>
        <i class="fas fa-star-half-alt"></i>
      <%#end  %>
      <%# if @rating != 0 %>
        <%#= @rating.count %>
      <%# end %>

        <h2> <%= @open %> <%= @fermeture%></h2>

    <p><%#= @stock.product.name %></p>
    <p><%= @stock.price %>$</p>


    -->




  </div>
</div>







<!-- Modal -->

<!-- ModalNewFavorite -->
<% unless @favorite_user.include? @stock.product.id  %>
  <!-- ModalNewFavorite -->
  <div class="modal fade" id="ModalNewFavorite" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg h-75" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div class="container mt-4 text-center">
            <h5>Voulez-vous ajouter <strong><%= @stock.product.name %></strong> aux favoris ?</h5>
            <div class="mx-5 d-flex justify-content-center">
              <%= simple_form_for [@stock, @favorite] do |f| %>
                <%= f.submit 'Oui', class: 'btn btn-success m-4' %>
              <% end %>
              <button type="button" class="btn btn-warning m-4" data-dismiss="modal">Non</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>


<script>

  const div = document.getElementById('geocoder-2');
  const displayS = (d) => {
    if (d.style.display === "none") {
      d.style.display = "block";
    } else {
      d.style.display = "none";
    }};
  const search = document.getElementById('btn-add-2');
  search.addEventListener('click', (event) => {
    displayS(div);
  });


</script>