config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 root to: 'searches#index'

 resources :products do
    get :get_barcode, on: :collection
  end

resources :searches, only:[:index,:new, :create], shallow: true do
    resources :stocks, only:[:index, :show], shallow: true do
      resources :reviews, only:[:show, :new, :create]
      resources :favorites, only:[:create]
      resources :baskets, only:[:create]
    end
end
  resources :favorites, only:[:index, :destroy]
  resources :baskets, only:[:index, :destroy]
  resources :itinaries, only: [:index]
end

app/models/search.rb
class Search < ApplicationRecord
  has_many :products
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    #Product.reindex # avec "Elastic"
    #@products = Product.all #"Sans Elastic"
   # Product.reindex # avec "Elastic"
     @events = Event.order(:start_date)
  end





  def new
  end

  def create
    #@products = Product.all
    @products = Product.searchable_by(params[:query])
    p @products
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js  # <-- will render `app/views/searches/create.js.erb`
      end
  end






end

app/views/searches/_searches_results.html.erb
<div id="results">
<ul>
  <% if @products.nil?  %>
  <% elsif @products.size == 0  %>

      <h3 class="text-center m-4  " style="font-size: 20px; color: white;">désolé, nous n'avons trouvé aucun produit correspondant...</h3>

  <% else %>
    <% @products.each do |product|  %>
      <li>
        <div class="card-product rounded rounded-pill">
          <%= cl_image_tag product.photo.key%>
          <!-- <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> -->
          <div class="card-product-infos">
            <h2><%= link_to product.name, search_stocks_path(product) %></h2>
          </div>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>
</div>

app/views/searches/create.js.erb
// function refreshForm(innerHTML) {
//   const newReviewForm = document.getElementById('search');
//   newReviewForm.innerHTML = innerHTML;
// }

function addResult(resultHTML) {
  const results = document.getElementById('list-results');
  results.innerHTML = resultHTML  ;

  // results.insertAdjacentHTML('beforeend', resultHTML);
}

  addResult('<%= j render "searches_results", products: @products %>');

app/views/searches/index.html.erb
<div class="home-page">
  <nav class="navbar navbar-expand-sm bg-transparent justify-content-end" id="nav">
  <div class="lily-logo">
    <!-- <h1 id="mini-title" class="text-center my-2 text-white">ShopChop!</h1> -->
    <div class="mini-logo_lily"></div>
  </div>


  <!-- Burger -->
  <div class="dropdown dropleft">
    <button class="btn bg-transparent border-transparent shadow-none px-1" type="button" data-toggle="dropdown"><i class="fas fa-bars fa-1x" style="color: white;"></i>
        </button>
      <% if user_signed_in? %>
        <div class="dropdown-menu rounded border-0" aria-labelledby="dropdownMenu2">
          <%= link_to favorites_path do %>
          <button class="dropdown-item" type="button">Favoris</button>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <button class="dropdown-item" type="button">Log out</button>
          <% end %>
        </div>
      <% else %>
        <div class="dropdown-menu rounded border-0" aria-labelledby="dropdownMenu2">
          <%= link_to new_user_session_path do %>
          <button class="dropdown-item" type="button">Login</button>
          <% end %>
        </div>
      <% end %>
  </div>
</nav>
<div id="chop-container" class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-lg-6">
      <div class="lily" id="lily">
      </div>
      <%#= image_tag "lily_70.png", class: "mx-auto d-block", id: "lily" %>
      <h1 id="main-title" class="text-center my-2 text-white">ChopShop!</h1>
    </div>
  </div>
</div>
<!-- Container Search -->
<!-- Container Search -->
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-lg-6">

 <!-- Search form -->

            <div class="input-group-append p-2 bg-white rounded rounded-pill d-flex justify-content-between search-bar">

              <%= link_to products_path do %>
                <i class="fas fa-barcode shadow-none pt-1 px-4" style="font-size: 30px; color: #F4AA5B;"></i>
              <% end %>

              <%= link_to new_search_path, class:'border-0 shadow-none bg-transparent btn', style:"color:#848D91;" do %>
                "Recherchez un produit..."
              <% end %>

              <span class='border-0 shadow-none bg-transparent flex-grow-1'></span>

              <%= link_to new_search_path, class:'border-0 shadow-none bg-transparent btn' do %>
                  <i class="fa fa-search shadow-none" style="color: #F4AA5B;"></i>
              <% end %>
            </div>


<!-- Fin search form -->


    </div>
  </div>
<div class="card-event-container display-card ">
      <% if @events.event_today? %>
        <div class="today">
          <h2>Aujourd'hui</h2>
          <div class="border-foufou"></div>
        </div>
        <% @events.return_today_event.each do |event| %>
           <div class="card-test" >
            <div class="image-event-test" data-toggle="modal" data-target="#event<%=event.id %>" style="background-image: url('<%= cl_image_path event.photo.key, height: 300, width: 400, crop: :fill %>')">
              <div class="date-event">

              </div>
            </div>
            <div class="card-cat">
              <h3><%= event.category %></h3>
            </div>
            <div class="card-info-test" data-toggle="modal" data-target="#event<%=event.id %>">
              <div class="main-info-test">
                <h3><%= event.name %></h3>
                <p><%= event.description %></p>
                <p><%= event.address %></p>
              </div>
              <div class="date-info-test">
                <% if event.end_date.day == event.start_date.day && event.month == event.month %>
                  <p><%= event.start_date.day  %> <%= event.month %>  <%= event.start_date.year %></p>
                <% elsif event.month == event.month %>
                  <p><%= event.start_date.day %>/<%= event.end_date.day %> <%= events.month %> <%= event.start_date.year %></p>
                <% else %>
                  <p><%= event.start_date.day %> - <%= event.month %> / <%= event.end_date.day %> - <%= event.month2 %> <%= event.start_date.year %></p>
                <% end %>

              </div>
            </div>
          </div>
         <% end %>
      <% end %>
        <div class="today">
          <h2>Evènements à venir</h2>
          <div class="border-foufou2"></div>
        </div>
        <% (@events - @events.return_today_event).each do |event|  %>
          <% if event.start_date > Date.today %>

            <div class="card-test">
              <div class="image-event-test" data-toggle="modal" data-target="#event<%=event.id %>" style="background-image: url('<%= cl_image_path event.photo.key, height: 300, width: 400, crop: :fill %>')">
                <div class="date-event">

                </div>
              </div>
              <div class="card-cat">
                <h3><%= event.category %></h3>
              </div>
              <div class="card-info-test" data-toggle="modal" data-target="#event<%=event.id %>">
                <div class="main-info-test">
                  <h3><%= event.name %></h3>
                  <p><%= event.description %></p>
                  <p><%= event.address %></p>
                </div>
                <div class="date-info-test">
                  <% if event.end_date.day == event.start_date.day && event.start_date.month == event.end_date.month %>
                    <p><%= event.start_date.day  %> <%= event.month %>  <%= event.start_date.year %></p>
                  <% elsif event.start_date.month == event.end_date.month %>
                    <p><%= event.start_date.day %>/<%= event.end_date.day %> <%= event.month %> <%= event.start_date.year %></p>
                  <% else %>
                    <p><%= event.start_date.day %> - <%= event.month %> / <%= event.end_date.day %> - <%= event.month2 %> <%= event.start_date.year %></p>
                  <% end %>

                </div>
              </div>
            </div>
          <% end %>
        <% end %>
</div>


<!-- MODAL -->
    <% @events.each do |event| %>
    <div class="modal fade" id="event<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content font-modal modal-content-rounded">
          <div class="modal-header">
            <div class="modal-title" id="exampleModalLongTitle">
              <%= cl_image_tag event.photo.key ,class:"img-event-modal pl-4"%>
              <h4 class="d-flex justify-content-center pt-4">
                <strong><%= event.name %></strong>
              </h4>
            </div>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="d-flex justify-content-between pb-2 text-orange">
              <div>
                <% if event.start_date == event.end_date%>
                <%= "Le #{event.start_date.day} #{event.month} #{event.start_date.year}" %>
                <% else %>
                <div class="d-block">
                <p><%= "Du : #{event.start_date.day} #{event.month} #{event.start_date.year}" %></p>
                <p><%= "Au: #{event.end_date.day} #{event.month} #{event.end_date.year}" %></p>
                </div>
                <% end %>
              </div>
              <div>
                <%= event.category.capitalize %>
              </div>
            </div>
            <div class="text-orange pb-4 border-bottom">
              <i class="fas fa-map-marked-alt"></i>
              <em><%= event.address %></em>
            </div>
            <div class="pt-3">
              <%= event.description %>
            </div>
          </div>
          <div class="modal-footer d-flex justify-content-center">
            <button type="button" class="btn btn-warning text-white">J'y vais!</button>
          </div>
        </div>
      </div>
    </div>
  <%end %>

  <div class="event-btn">
    <i class="fas fa-calendar-alt"></i>
          <% if @events.event_today? %>
            <p class="notiti"><%= @events.all_event_today %></p>
          <% end %>
  </div>
<!-- <h1>Searches#new</h1> -->
</div>

app/views/searches/new.html.erb
<div class="home-page">

  <nav class="navbar navbar-expand-sm bg-transparent justify-content-between" id="nav">

    <%= link_to "/" do %>
      <%= image_tag "lily_35.png" %>
     <% end %>

  <!-- Burger -->
  <div class="dropdown dropleft">
    <button class="btn bg-transparent border-transparent shadow-none px-1" type="button" data-toggle="dropdown"><i class="fas fa-bars fa-1x" style="color: white;"></i>
        </button>
      <% if user_signed_in? %>
        <div class="dropdown-menu rounded border-0" aria-labelledby="dropdownMenu2">
          <%= link_to baskets_path do %>
          <button class="dropdown-item" type="button">Panier</button>
          <% end %>
          <%= link_to favorites_path do %>
          <button class="dropdown-item" type="button">Favoris</button>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <button class="dropdown-item" type="button">Log out</button>
          <% end %>
        </div>
      <% else %>
        <div class="dropdown-menu rounded border-0" aria-labelledby="dropdownMenu2">
          <%= link_to new_user_session_path do %>
          <button class="dropdown-item" type="button">Login</button>
          <% end %>
        </div>
      <% end %>
  </div>

</nav>


<!-- Container Search -->

  <div class="container my-4" id="research">
    <h1 id="main-title" class="text-center my-4 text-white">ChopShop!</h1>
    <div class="row justify-content-center">

   <!-- Search form -->
        <div class="flex-grow-1 mx-4">
            <div class="bg-white rounded rounded-pill d-flex p-2">
                <%= link_to products_path do %>
                  <i class="fas fa-barcode shadow-none pt-1" style="font-size: 30px; color: #ffcd3c;"></i>
                <%  end %>
                <div  class="flex-grow-1">
                  <%= form_tag searches_path, method: :post, autocomplete: :off, id:"search", remote: true do %>
                    <div class="d-flex justify-content-between">
                      <%= text_field_tag :query,
                        params[:query],
                        id: "myForm",
                        class:"form-control typeahead border-0 shadow-none bg-transparent align-middle",
                        placeholder: "Recherchez un produit...",
                        autofocus: "true"
                      %>
                      <%= button_tag :submit, id:"search_button", class:'border-0 shadow-none bg-transparent btn' do %>
                          <i class="fa fa-search shadow-none" style="color: #ffcd3c;"></i>
                      <% end %>
                    </div>
                  <% end %>
                </div>
            </div>
        </div>
  <!-- Fin search form -->
    </div> <!-- fin de la row -->
    <!-- results -->
    <div class="col-sm-12 col-lg-12" id="list-results">
        <%#= render "_searches_results", products: @products %>
    </div>
  </div> <!-- fin du container -->

  <!-- affichage du logo sous les resultats -->
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-lg-6">
          <div class="lily" id="lily"></div>

      </div>
    </div>
  </div>

</div> <!-- #fin de la home -->












  </div>
</div>




<!-- <h1>Searches#new</h1> -->

</div>